class article:
    title: str
    article_text: str
    article_url: str
    author: str
    def getTitle(self):
        return self.title
    def getText(self):
        return self.article_text
    def getUrl(self):
        return self.article_url
    def getAuthor(self):
        return self.author
